storage: /verdaccio/storage
auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    max_users: -1
web:
  enable: true
  title: "Npm"
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@some-packet/*":
    access: $authenticated
    publish: user
  "@*/*":
    access: $all
    publish: $authenticated
    proxy: npmjs
  "**":
    access: $all
    publish: $all
    proxy: npmjs
publish:
  allow_offline: true
logs:
  - { type: stdout, format: pretty, level: http }